name: usta_takapp
description: Usta Takip mobil uygulamasÄ±
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  flutter_riverpod: ^2.5.0
  path_provider: ^2.1.1
  open_filex: ^4.3.2
  pdf: ^3.10.7
  excel: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
